### ISSUE TITLE
Save Annoton does not always work

### ISSUE THREAD

**Issue by cmungall** [DoctorBud/tableview-workbench#8]
Eg in 5993df9e00000037

![image](https://user-images.githubusercontent.com/50745/29467397-3f9fdb2e-83f5-11e7-8bed-d7576a6ee81f.png)

I updated the PMID to PMID:999999. I click Save Annoton. The save is not reflected in the table below, as can be seen in the screenshot. Also not in the graphical view.

If I click + in the row it reverts the value back to PMID:123456

It also appears to be impossible to add evidence to the other aspects of the annoton:

![image](https://user-images.githubusercontent.com/50745/29467505-a8e5e934-83f5-11e7-96de-025278473060.png)

Note also stray rows at bottom. Not sure if this is related:

![image](https://user-images.githubusercontent.com/50745/29467535-c09632aa-83f5-11e7-9c0f-0c1faa99bf51.png)

cc @kltm

**Comment by DoctorBud** [comment]
Unless this is duplicable by me (I hope it is), it is VERY helpful for a bug submitter to include the output of the JS Console, especially if there are Red Text error messages. In this case, I suspect that an error occurred and that a useful message was present in the console.

**Comment by cmungall** [comment]
should be easy to duplicate but here is the console output when Save Annoton is clicked:

```
error: a {_is_a: "bbop-response-barista", _raw: {…}, _okay: true, _message: "Could not successfully handle batch request. Excep…non-null value for: request.arguments.expressions", _message_type: "error", …}_commentary: "org.geneontology.minerva.server.handler.OperationsTools$MissingParameterException: Expected non-null value for: request.arguments.expressions↵	at org.geneontology.minerva.server.handler.OperationsTools.requireNotNull(OperationsTools.java:19)↵	at org.geneontology.minerva.server.handler.OperationsImpl.handleRequestForIndividual(OperationsImpl.java:155)↵	at org.geneontology.minerva.server.handler.JsonOrJsonpBatchHandler.m3Batch(JsonOrJsonpBatchHandler.java:156)↵	at org.geneontology.minerva.server.handler.JsonOrJsonpBatchHandler.m3Batch(JsonOrJsonpBatchHandler.java:132)↵	at org.geneontology.minerva.server.handler.JsonOrJsonpBatchHandler.m3BatchPostPrivileged(JsonOrJsonpBatchHandler.java:91)↵	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)↵	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)↵	at java.lang.reflect.Method.invoke(Method.java:498)↵	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)↵	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)↵	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)↵	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:195)↵	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)↵	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:402)↵	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:349)↵	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:106)↵	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:259)↵	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)↵	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)↵	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)↵	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)↵	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)↵	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:318)↵	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:236)↵	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1010)↵	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)↵	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:382)↵	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:345)↵	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:220)↵	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:547)↵	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:480)↵	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)↵	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:941)↵	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:409)↵	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)↵	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:875)↵	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)↵	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)↵	at org.eclipse.jetty.server.Server.handle(Server.java:349)↵	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:441)↵	at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:936)↵	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:801)↵	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:224)↵	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)↵	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)↵	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)↵	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)↵	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)↵	at java.lang.Thread.run(Thread.java:748)↵"_data: null_groups: null_intention: "action"_is_a: "bbop-response-barista"_message: "Could not successfully handle batch request. Exception: org.geneontology.minerva.server.handler.OperationsTools$MissingParameterException. Expected non-null value for: request.arguments.expressions"_message_type: "error"_okay: true_packet_id: "63f2f25f11e8211c8"_raw: {packet-id: "63f2f25f11e8211c8", uid: "http://orcid.org/0000-0002-6601-2165", provided-by: Array(0), is-reasoned: false, intention: "action", …}_reasoner_p: false_signal: "unknown"_uid: "http://orcid.org/0000-0002-6601-2165"__proto__: i error Could not successfully handle batch request. Exception: org.geneontology.minerva.server.handler.OperationsTools$MissingParameterException. Expected non-null value for: request.arguments.expressions
```

**Comment by cmungall** [comment]
This can also be duplicated easily from a scratch model:

Create an annoton:

 * GP: any
 * F: term, evidence, PMID (any values)
 * P: term only

Save Annoton

Edit Annoton

Try and modify PMID for the F aspect - same error

![image](https://user-images.githubusercontent.com/50745/29480498-8f73eb9e-842d-11e7-81eb-7bd42df75a8d.png)

**Comment by cmungall** [comment]
Attempting to delete also produces same error

**Comment by cmungall** [comment]
This was fixed
